baseURL = "https://dzisu.github.io/blog/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"

# Enable RSS feed
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

# Pagination
paginate = 10

# Reading time and word count
[params]
    author = "dzisu"
    description = "A personal blog built with Hugo and PaperMod theme"
    keywords = ["blog", "hugo", "papermod"]
    
    # Reading time
    ShowReadingTime = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    
    # Enable search
    fuseOpts = [
        "includeScore",
        "shouldSort",
        "location",
        "distance",
        "threshold",
        "findAllMatches",
        "minMatchCharLength",
        "keys"
    ]

    # Social links
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dzisu"

    [[params.socialIcons]]
    name = "rss"
    url = "index.xml"

# Main menu
[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 40

[[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 50

# Markup configuration
[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"

# Output formats
[outputs]
    home = ["HTML", "RSS", "JSON"]

# Privacy config
[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
