name = "PaperMod"
license = "MIT"
licenselink = "https://github.com/adityatelange/hugo-PaperMod/blob/master/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "https://github.com/adityatelange/hugo-PaperMod"
demosite = "https://adityatelange.github.io/hugo-PaperMod/"
tags = ["blog", "clean", "customizable", "dark", "light", "minimal", "multilingual", "personal", "responsive", "simple"]
features = ["responsive", "dark mode", "search", "multilingual"]
min_version = "0.112.4"

[author]
  name = "Aditya Telange"
  homepage = "https://github.com/adityatelange"

[original]
  name = "Paper"
  homepage = "https://github.com/nanxiaobei/hugo-paper"
  repo = "https://github.com/nanxiaobei/hugo-paper"
